# Configuration for Codecov (https://codecov.io)

codecov:
  # Use `develop` as the default branch
  branch: develop

ignore:
  - Tests
  - OneTimePasswordLegacyTests

coverage:
  status:
    patch:
      default:
        # Allow patch to be 0% covered without marking a PR with a failing status.
        target: 0
