# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

excluded:
  - Carthage
enabled_rules:
  - empty_count
  - missing_docs
disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - line_length
  - opening_brace
  - valid_docs
